default_agent: codingagent
agents:
  codingagent:
    name: codingagent
    entrypoint: src/runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::670326884047:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-cc928dc9c6
      execution_role_auto_create: false
      account: '670326884047'
      region: ap-southeast-2
      ecr_repository: 670326884047.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-coding-agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: codingagent-lE7IQU3dK8
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:670326884047:runtime/codingagent-lE7IQU3dK8
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-codingagent-builder
      execution_role: arn:aws:iam::670326884047:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-3e99a3f99b
      source_bucket: bedrock-agentcore-codebuild-sources-670326884047-ap-southeast-2
    memory:
      mode: STM_ONLY
      memory_id: codingagent_mem-5s8o4OA2la
      memory_arn: arn:aws:bedrock-agentcore:ap-southeast-2:670326884047:memory/codingagent_mem-5s8o4OA2la
      memory_name: codingagent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
