default_agent: planning
agents:
  planning:
    name: planning
    entrypoint: src/runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::494848961867:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-423614833c
      execution_role_auto_create: false
      account: '494848961867'
      region: ap-southeast-2
      ecr_repository: 494848961867.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-planning
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: planning-hp7R5F5PJ8
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:494848961867:runtime/planning-hp7R5F5PJ8
      agent_session_id: bdab5cd8-9255-4971-bb92-ece8dc741fe9
    codebuild:
      project_name: bedrock-agentcore-planning-builder
      execution_role: arn:aws:iam::494848961867:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-423614833c
      source_bucket: bedrock-agentcore-codebuild-sources-494848961867-ap-southeast-2
    memory:
      mode: STM_ONLY
      memory_id: planning_mem-SEIn8G5zMi
      memory_arn: arn:aws:bedrock-agentcore:ap-southeast-2:494848961867:memory/planning_mem-SEIn8G5zMi
      memory_name: planning_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
