default_agent: github
agents:
  github:
    name: github
    entrypoint: src/runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::494848961867:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-c0b0109d94
      execution_role_auto_create: false
      account: '494848961867'
      region: ap-southeast-2
      ecr_repository: 494848961867.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-github
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: github-J7dn2UBTj7
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:494848961867:runtime/github-J7dn2UBTj7
      agent_session_id: d967aebf-b2b0-478e-9bc8-6017155f954c
    codebuild:
      project_name: bedrock-agentcore-github-builder
      execution_role: arn:aws:iam::494848961867:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-c0b0109d94
      source_bucket: bedrock-agentcore-codebuild-sources-494848961867-ap-southeast-2
    memory:
      mode: STM_AND_LTM
      memory_id: github_mem-cq7n1YBMRV
      memory_arn: null
      memory_name: github_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration:
      workload_name: github-agent-workload
      credential_providers:
      - github-provider
