default_agent: jira
agents:
  jira:
    name: jira
    entrypoint: src/runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::670326884047:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-c0b0109d94
      execution_role_auto_create: false
      account: '670326884047'
      region: ap-southeast-2
      ecr_repository: 670326884047.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-jira_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: jira_agent-WboCCb8qfb
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:670326884047:runtime/jira_agent-WboCCb8qfb
      agent_session_id: 4237f510-5de6-48c2-b826-fbb6ee31955d
    codebuild:
      project_name: bedrock-agentcore-jira_agent-builder
      execution_role: arn:aws:iam::670326884047:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-c0b0109d94
      source_bucket: bedrock-agentcore-codebuild-sources-670326884047-ap-southeast-2
    memory:
      mode: STM_ONLY
      memory_id: jira_mem-placeholder
      memory_arn: arn:aws:bedrock-agentcore:ap-southeast-2:670326884047:memory/jira_mem-placeholder
      memory_name: jira_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration:
      workload_name: jira-agent-workload
      credential_providers:
      - jira-provider
